#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This file is used to show how to store api keys. The file should be copied
# to the root as api_keys.py and the dummy keys replaced with your keys.
# Under no circumstances should api_keys.py be committed to a repository.

TUMBLR = {'consumer': 'dummy',
          'secret': 'dummy'}